coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 70%
        threshold: 5%

ignore:
  - "tests/"
  - "examples/"
  - "build/"
  - "_deps/"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
