if(EXISTS "/home/runner/work/tesla-ble/tesla-ble/_codeql_build_dir/tests/test_key_generation[1]_tests.cmake")
  include("/home/runner/work/tesla-ble/tesla-ble/_codeql_build_dir/tests/test_key_generation[1]_tests.cmake")
else()
  add_test(test_key_generation_NOT_BUILT test_key_generation_NOT_BUILT)
endif()
