if(EXISTS "/home/runner/work/tesla-ble/tesla-ble/_codeql_build_dir/tests/test_vehicle[1]_tests.cmake")
  include("/home/runner/work/tesla-ble/tesla-ble/_codeql_build_dir/tests/test_vehicle[1]_tests.cmake")
else()
  add_test(test_vehicle_NOT_BUILT test_vehicle_NOT_BUILT)
endif()
