if(EXISTS "/home/runner/work/tesla-ble/tesla-ble/_codeql_build_dir/tests/test_error_handling[1]_tests.cmake")
  include("/home/runner/work/tesla-ble/tesla-ble/_codeql_build_dir/tests/test_error_handling[1]_tests.cmake")
else()
  add_test(test_error_handling_NOT_BUILT test_error_handling_NOT_BUILT)
endif()
