if(EXISTS "/home/runner/work/tesla-ble/tesla-ble/_codeql_build_dir/tests/test_tb_utils[1]_tests.cmake")
  include("/home/runner/work/tesla-ble/tesla-ble/_codeql_build_dir/tests/test_tb_utils[1]_tests.cmake")
else()
  add_test(test_tb_utils_NOT_BUILT test_tb_utils_NOT_BUILT)
endif()
