/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_KEYS_KEYS_PB_H_INCLUDED
#define PB_KEYS_KEYS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Keys_Role {
    Keys_Role_ROLE_NONE = 0,
    Keys_Role_ROLE_SERVICE = 1,
    Keys_Role_ROLE_OWNER = 2,
    Keys_Role_ROLE_DRIVER = 3,
    Keys_Role_ROLE_FM = 4,
    Keys_Role_ROLE_VEHICLE_MONITOR = 5,
    Keys_Role_ROLE_CHARGING_MANAGER = 6
} Keys_Role;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Keys_Role_MIN Keys_Role_ROLE_NONE
#define _Keys_Role_MAX Keys_Role_ROLE_CHARGING_MANAGER
#define _Keys_Role_ARRAYSIZE ((Keys_Role)(Keys_Role_ROLE_CHARGING_MANAGER+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
