/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_CARSERVER_VEHICLE_PB_H_INCLUDED
#define PB_CARSERVER_VEHICLE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _CarServer_ClimateState_CopActivationTemp {
    CarServer_ClimateState_CopActivationTemp_CopActivationTempUnspecified = 0,
    CarServer_ClimateState_CopActivationTemp_CopActivationTempLow = 1,
    CarServer_ClimateState_CopActivationTemp_CopActivationTempMedium = 2,
    CarServer_ClimateState_CopActivationTemp_CopActivationTempHigh = 3
} CarServer_ClimateState_CopActivationTemp;

/* Struct definitions */
typedef struct _CarServer_VehicleState_GuestMode {
    bool GuestModeActive;
} CarServer_VehicleState_GuestMode;

typedef struct _CarServer_VehicleState {
    bool has_guestMode;
    CarServer_VehicleState_GuestMode guestMode;
} CarServer_VehicleState;

typedef struct _CarServer_ClimateState {
    char dummy_field;
} CarServer_ClimateState;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _CarServer_ClimateState_CopActivationTemp_MIN CarServer_ClimateState_CopActivationTemp_CopActivationTempUnspecified
#define _CarServer_ClimateState_CopActivationTemp_MAX CarServer_ClimateState_CopActivationTemp_CopActivationTempHigh
#define _CarServer_ClimateState_CopActivationTemp_ARRAYSIZE ((CarServer_ClimateState_CopActivationTemp)(CarServer_ClimateState_CopActivationTemp_CopActivationTempHigh+1))





/* Initializer values for message structs */
#define CarServer_VehicleState_init_default      {false, CarServer_VehicleState_GuestMode_init_default}
#define CarServer_VehicleState_GuestMode_init_default {0}
#define CarServer_ClimateState_init_default      {0}
#define CarServer_VehicleState_init_zero         {false, CarServer_VehicleState_GuestMode_init_zero}
#define CarServer_VehicleState_GuestMode_init_zero {0}
#define CarServer_ClimateState_init_zero         {0}

/* Field tags (for use in manual encoding/decoding) */
#define CarServer_VehicleState_GuestMode_GuestModeActive_tag 1
#define CarServer_VehicleState_guestMode_tag     74

/* Struct field encoding specification for nanopb */
#define CarServer_VehicleState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  guestMode,        74)
#define CarServer_VehicleState_CALLBACK NULL
#define CarServer_VehicleState_DEFAULT NULL
#define CarServer_VehicleState_guestMode_MSGTYPE CarServer_VehicleState_GuestMode

#define CarServer_VehicleState_GuestMode_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     GuestModeActive,   1)
#define CarServer_VehicleState_GuestMode_CALLBACK NULL
#define CarServer_VehicleState_GuestMode_DEFAULT NULL

#define CarServer_ClimateState_FIELDLIST(X, a) \

#define CarServer_ClimateState_CALLBACK NULL
#define CarServer_ClimateState_DEFAULT NULL

extern const pb_msgdesc_t CarServer_VehicleState_msg;
extern const pb_msgdesc_t CarServer_VehicleState_GuestMode_msg;
extern const pb_msgdesc_t CarServer_ClimateState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CarServer_VehicleState_fields &CarServer_VehicleState_msg
#define CarServer_VehicleState_GuestMode_fields &CarServer_VehicleState_GuestMode_msg
#define CarServer_ClimateState_fields &CarServer_ClimateState_msg

/* Maximum encoded size of messages (where known) */
#define CARSERVER_VEHICLE_PB_H_MAX_SIZE          CarServer_VehicleState_size
#define CarServer_ClimateState_size              0
#define CarServer_VehicleState_GuestMode_size    2
#define CarServer_VehicleState_size              5

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
