/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "signatures.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Signatures_KeyIdentity, Signatures_KeyIdentity, AUTO)


PB_BIND(Signatures_AES_GCM_Personalized_Signature_Data, Signatures_AES_GCM_Personalized_Signature_Data, AUTO)


PB_BIND(Signatures_HMAC_Signature_Data, Signatures_HMAC_Signature_Data, AUTO)


PB_BIND(Signatures_HMAC_Personalized_Signature_Data, Signatures_HMAC_Personalized_Signature_Data, AUTO)


PB_BIND(Signatures_SignatureData, Signatures_SignatureData, AUTO)


PB_BIND(Signatures_GetSessionInfoRequest, Signatures_GetSessionInfoRequest, AUTO)


PB_BIND(Signatures_SessionInfo, Signatures_SessionInfo, AUTO)









