/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "universal_message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(UniversalMessage_Destination, UniversalMessage_Destination, AUTO)


PB_BIND(UniversalMessage_MessageStatus, UniversalMessage_MessageStatus, AUTO)


PB_BIND(UniversalMessage_SessionInfoRequest, UniversalMessage_SessionInfoRequest, AUTO)


PB_BIND(UniversalMessage_RoutableMessage, UniversalMessage_RoutableMessage, 2)







