/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "vehicle.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CarServer_VehicleState, CarServer_VehicleState, 2)


PB_BIND(CarServer_VehicleState_GuestMode, CarServer_VehicleState_GuestMode, AUTO)


PB_BIND(CarServer_ClimateState, CarServer_ClimateState, AUTO)





